### ISSUE TITLE
Mask the initial ERROR removing host if it doesn't exist

### ISSUE THREAD

**Issue by ajeetraina** [thesandlord/google-cloud-swarm#2]
It will be good if docker-machine rm -f $PREFIX-manager-$i && under swarm-up.sh does just a quick check and report back that the $PREFIX-manager1 doesn't exist as an information rather than the script throwing huge number of error messages:

Error removing host "collab-manager-1": Host does not exist: "collab-manager-1"
Can't remove "collab-manager-1"
About to remove collab-worker-1
Error removing host "collab-worker-1": Host does not exist: "collab-worker-1"
Can't remove "collab-worker-1"
About to remove collab-worker-2
Error removing host "collab-worker-2": Host does not exist: "collab-worker-2"
Can't remove "collab-worker-2"

Otherwise, a good timesaving tool.

**Comment by thesandlord** [comment]
Probably going to move from docker-machine commands to [Managed Instance Groups](https://cloud.google.com/compute/docs/instance-groups/), which will make it faster, more scalable, and remove this issue.

**Comment by thesandlord** [comment]
No longer using docker-machine for VM creation, so these errors no longer show up.
