### ISSUE TITLE
Recommend test.docker.com for ENGINE_INSTALL_URL variable under options.sh 

### ISSUE THREAD

**Issue by ajeetraina** [thesandlord/google-cloud-swarm#3]
I recommend test.docker.com instead of experimental.docker.com which gets the latest 1.12-rc3 release installed and swarm mode working. While I used experimental.docker.com, it pulled 1.11 instead of 1.12.

**Comment by thesandlord** [comment]
Using the "testing" repo for Ubuntu 16.04

Will switch to "release" once 1.12 is official
