### ISSUE TITLE
Missing --listen-addr $masterip under swarm-up.sh

### ISSUE THREAD

**Issue by ajeetraina** [thesandlord/google-cloud-swarm#4]
Under swam-up.sh, --listen-addr $masterip:2377 is missing due to which docker swarm doesnt get created. The right command is:

docker swarm init --listen-addr $SWARM_MANAGER_INTERNAL_IP:2377 --secret $SWARM_SECRET

**Comment by thesandlord** [comment]
Swarm will default to localhost:2377 if a --listen-addr is not provided. It's working fine for me, I can't reproduce this issue.
